import { GOOGLE_BOOK_API_ACCESS_HISTORY_TRANSACTION_FILE, TRANSACTION_FILE_PATH } from "../../../util/const/FileInfoConst";

// Google Books Apiアクセストランザクションファイルパス
export const GOOGLE_BOOK_API_ACCESS_HISTORY_TRANSACTION_FILE_PATH = `${TRANSACTION_FILE_PATH}${GOOGLE_BOOK_API_ACCESS_HISTORY_TRANSACTION_FILE}`;
