import { TRANSACTION_FILE_PATH, GOOGLE_BOOKS_API_SMALLTHUMBNAIL_CACHE_FILE } from "../../../util/const/FileInfoConst";

// Google Books Apiサムネイル(小)キャッシュファイルパス
export const GOOGLE_BOOKS_API_SMALLTHUMBNAIL_CACHE_FILE_PATH = `${TRANSACTION_FILE_PATH}${GOOGLE_BOOKS_API_SMALLTHUMBNAIL_CACHE_FILE}`;
